### PR TITLE
Fixed expect_check() and expect_in_set()

### PR DESCRIPTION
**Pull request by zr5dt**
During routine testing I discovered that expect_check() and expect_in_set() were broken. Please consider the following patch to fix them.

### CODE REVIEW

**Comment by lpabon** [comment]
Hi @zr5dt , this looks good, but do you mind providing or modifying the unit tests to check for this?  Thank you.

**Comment by lpabon** [comment]
This part is new to me.  Do you mind explaining why this was broken before and how it works now?  Thank you.

**Comment by zr5dt** [comment]
Hi Luis,

Yes, I’ll do that.

Regards
Dario

**Comment by zr5dt** [comment]
The “expect_check()” macro was passing a “count” value of 0 to the _expect_check() function. This meant that nothing would be added to the expect queue.

The "expect_in_set()” function was not storing the number of values in a given set so that, when it came time to check against that set, there was either zero or a random value for the size of the set.

# Dario

**Comment by zr5dt** [comment]
I have updated my "expect-fix" branch with some simple unit tests. Located at "src/examples/game.c" and
"src/examples/game_test.c". When the example is built on the master branch, it produces a false failure. When it is built on the expect-fix branch, it produces a true pass.

**Comment by lpabon** [comment]
Took me a while to review this, but now I see the issues as pointed out by the unit tests.  Great job finding the bugs and fixing them.  Thank you @zr5dt !

**Comment by zr5dt** [comment]
Most welcome. Thanks for maintaining cmockery2

- Dario

**Pull request merged**
